import { ReactNode } from "react";

export type WorkItem = {
  title: string;
  sub: string[];
  desc: ReactNode;
  src: string;
  alt: string;
};

export const WORKS_PROFESSIONAL: WorkItem[] = [
  {
    title: "Plicar Impact Demo",
    sub: ["@reconlabs", "2023.12 - 2024.01"],
    desc: (
      <>
        Interactive webapp designed for new type of visual attraction.
        <br className="hidden md:block" />
        Using assets generated by 3D Gaussian Splatting.
      </>
    ),
    src: "/works/professional/plicar-demo",
    alt: "Plicar Impact Demo - Click for more detail",
  },
  {
    title: "Reconlabs UI (RUI)",
    sub: ["@reconlabs", "2023.08 - 2023.09"],
    desc: (
      <>
        React component library for Reconlabs front-end dev team.
        <br className="hidden md:block" />
        Packaged and published, documented with Storybook.
      </>
    ),
    src: "/works/professional/rui",
    alt: "Reconlabs UI - Click for more detail",
  },
  {
    title: "3Dpresso x ZEPETO",
    sub: ["@reconlabs", "2023.07"],
    desc: (
      <>
        Collaboration project with ZEPETO (3D Metaverse Platform)
        <br className="hidden md:block" />
        AI Generated fashion item creator webapp.
      </>
    ),
    src: "/works/professional/zepeto",
    alt: "3Dpresso and ZEPETO - Click for more detail",
  },
  {
    title: "3Dpresso",
    sub: ["@reconlabs", "2023.01 - 2023.11"],
    desc: (
      <>
        AI 3D Generation service for 3D content creators.
        <br className="hidden md:block" />
        Generates 3D models with various inputs (video, prompts, drawings)
      </>
    ),
    src: "/works/professional/3dpresso",
    alt: "3Dpresso - Click for more detail",
  },
];

export const WORKS_PERSONAL: WorkItem[] = [
  {
    title: "Ainokatachi (The Shape of Love)",
    sub: ["2024.03"],
    desc: (
      <>
        Mini interactive web visualizing various shapes of love.
        <br className="hidden md:block" />
        SVG Morphing based on story telling.
      </>
    ),
    src: "/works/personal/ainokatachi",
    alt: "Ainokatachi - Click for more detail",
  },
  {
    title: "Open House Invitation",
    sub: ["2023.11"],
    desc: (
      <>
        3D Interactive web for a *hypothetical* open house party.
        <br />
        (Caution : not optimized enough)
      </>
    ),
    src: "/works/personal/open_house",
    alt: "Open House Invitation - Click for more detail",
  },
];
